name: Latest

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * 0"

env:
  TEST_TAG: y0utubesir/alle2e:latest-test
  OFFICIAL_TAG: y0utubesir/alle2e:latest
  MAIN_REPO_NAME: y0utubesir/alle2e
  DOCKERFILE_PATH: ./Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and export to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.DOCKERFILE_PATH }}
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Remove Test Image from DockerHub
        run: |
          echo "Test was successful, removing test image"
          docker run --rm ${{ env.TEST_TAG }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.DOCKERFILE_PATH }}
          platforms: linux/amd64
          push: true
          tags: ${{ env.OFFICIAL_TAG }}
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: ${{ env.MAIN_REPO_NAME }}
          readme-filepath: ./README.md